// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteV1AdminUsersUserOKCode is the HTTP code returned for type DeleteV1AdminUsersUserOK
const DeleteV1AdminUsersUserOKCode int = 200

/*DeleteV1AdminUsersUserOK Deleted

swagger:response deleteV1AdminUsersUserOK
*/
type DeleteV1AdminUsersUserOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteV1AdminUsersUserOK creates DeleteV1AdminUsersUserOK with default headers values
func NewDeleteV1AdminUsersUserOK() *DeleteV1AdminUsersUserOK {

	return &DeleteV1AdminUsersUserOK{}
}

// WithPayload adds the payload to the delete v1 admin users user o k response
func (o *DeleteV1AdminUsersUserOK) WithPayload(payload string) *DeleteV1AdminUsersUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete v1 admin users user o k response
func (o *DeleteV1AdminUsersUserOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteV1AdminUsersUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteV1AdminUsersUserUnauthorizedCode is the HTTP code returned for type DeleteV1AdminUsersUserUnauthorized
const DeleteV1AdminUsersUserUnauthorizedCode int = 401

/*DeleteV1AdminUsersUserUnauthorized Unauthorized

swagger:response deleteV1AdminUsersUserUnauthorized
*/
type DeleteV1AdminUsersUserUnauthorized struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteV1AdminUsersUserUnauthorized creates DeleteV1AdminUsersUserUnauthorized with default headers values
func NewDeleteV1AdminUsersUserUnauthorized() *DeleteV1AdminUsersUserUnauthorized {

	return &DeleteV1AdminUsersUserUnauthorized{}
}

// WithPayload adds the payload to the delete v1 admin users user unauthorized response
func (o *DeleteV1AdminUsersUserUnauthorized) WithPayload(payload string) *DeleteV1AdminUsersUserUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete v1 admin users user unauthorized response
func (o *DeleteV1AdminUsersUserUnauthorized) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteV1AdminUsersUserUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteV1AdminUsersUserForbiddenCode is the HTTP code returned for type DeleteV1AdminUsersUserForbidden
const DeleteV1AdminUsersUserForbiddenCode int = 403

/*DeleteV1AdminUsersUserForbidden forbidden

swagger:response deleteV1AdminUsersUserForbidden
*/
type DeleteV1AdminUsersUserForbidden struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteV1AdminUsersUserForbidden creates DeleteV1AdminUsersUserForbidden with default headers values
func NewDeleteV1AdminUsersUserForbidden() *DeleteV1AdminUsersUserForbidden {

	return &DeleteV1AdminUsersUserForbidden{}
}

// WithPayload adds the payload to the delete v1 admin users user forbidden response
func (o *DeleteV1AdminUsersUserForbidden) WithPayload(payload string) *DeleteV1AdminUsersUserForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete v1 admin users user forbidden response
func (o *DeleteV1AdminUsersUserForbidden) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteV1AdminUsersUserForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteV1AdminUsersUserNotFoundCode is the HTTP code returned for type DeleteV1AdminUsersUserNotFound
const DeleteV1AdminUsersUserNotFoundCode int = 404

/*DeleteV1AdminUsersUserNotFound The specified resource was not found

swagger:response deleteV1AdminUsersUserNotFound
*/
type DeleteV1AdminUsersUserNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteV1AdminUsersUserNotFound creates DeleteV1AdminUsersUserNotFound with default headers values
func NewDeleteV1AdminUsersUserNotFound() *DeleteV1AdminUsersUserNotFound {

	return &DeleteV1AdminUsersUserNotFound{}
}

// WithPayload adds the payload to the delete v1 admin users user not found response
func (o *DeleteV1AdminUsersUserNotFound) WithPayload(payload string) *DeleteV1AdminUsersUserNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete v1 admin users user not found response
func (o *DeleteV1AdminUsersUserNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteV1AdminUsersUserNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteV1AdminUsersUserInternalServerErrorCode is the HTTP code returned for type DeleteV1AdminUsersUserInternalServerError
const DeleteV1AdminUsersUserInternalServerErrorCode int = 500

/*DeleteV1AdminUsersUserInternalServerError For unknown or unanticipated issues

swagger:response deleteV1AdminUsersUserInternalServerError
*/
type DeleteV1AdminUsersUserInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteV1AdminUsersUserInternalServerError creates DeleteV1AdminUsersUserInternalServerError with default headers values
func NewDeleteV1AdminUsersUserInternalServerError() *DeleteV1AdminUsersUserInternalServerError {

	return &DeleteV1AdminUsersUserInternalServerError{}
}

// WithPayload adds the payload to the delete v1 admin users user internal server error response
func (o *DeleteV1AdminUsersUserInternalServerError) WithPayload(payload string) *DeleteV1AdminUsersUserInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete v1 admin users user internal server error response
func (o *DeleteV1AdminUsersUserInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteV1AdminUsersUserInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
