// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"github.com/momper14/edgex-restapp/models"
)

// NewDeleteV1AdminPoliciesParams creates a new DeleteV1AdminPoliciesParams object
// no default values defined in spec.
func NewDeleteV1AdminPoliciesParams() DeleteV1AdminPoliciesParams {

	return DeleteV1AdminPoliciesParams{}
}

// DeleteV1AdminPoliciesParams contains all the bound params for the delete v1 admin policies operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteV1AdminPolicies
type DeleteV1AdminPoliciesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Policy to process
	  Required: true
	  In: body
	*/
	Body *models.Policy
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteV1AdminPoliciesParams() beforehand.
func (o *DeleteV1AdminPoliciesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Policy
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body", ""))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
