// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/momper14/edgex-restapp/models"
)

// DeleteV1AdminRolesRoleHandlerFunc turns a function with the right signature into a delete v1 admin roles role handler
type DeleteV1AdminRolesRoleHandlerFunc func(DeleteV1AdminRolesRoleParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteV1AdminRolesRoleHandlerFunc) Handle(params DeleteV1AdminRolesRoleParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// DeleteV1AdminRolesRoleHandler interface for that can handle valid delete v1 admin roles role params
type DeleteV1AdminRolesRoleHandler interface {
	Handle(DeleteV1AdminRolesRoleParams, *models.User) middleware.Responder
}

// NewDeleteV1AdminRolesRole creates a new http.Handler for the delete v1 admin roles role operation
func NewDeleteV1AdminRolesRole(ctx *middleware.Context, handler DeleteV1AdminRolesRoleHandler) *DeleteV1AdminRolesRole {
	return &DeleteV1AdminRolesRole{Context: ctx, Handler: handler}
}

/*DeleteV1AdminRolesRole swagger:route DELETE /v1/admin/roles/{role} deleteV1AdminRolesRole

Deletes the role

*/
type DeleteV1AdminRolesRole struct {
	Context *middleware.Context
	Handler DeleteV1AdminRolesRoleHandler
}

func (o *DeleteV1AdminRolesRole) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteV1AdminRolesRoleParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
