// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteV1AdminPoliciesOKCode is the HTTP code returned for type DeleteV1AdminPoliciesOK
const DeleteV1AdminPoliciesOKCode int = 200

/*DeleteV1AdminPoliciesOK Deleted

swagger:response deleteV1AdminPoliciesOK
*/
type DeleteV1AdminPoliciesOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteV1AdminPoliciesOK creates DeleteV1AdminPoliciesOK with default headers values
func NewDeleteV1AdminPoliciesOK() *DeleteV1AdminPoliciesOK {

	return &DeleteV1AdminPoliciesOK{}
}

// WithPayload adds the payload to the delete v1 admin policies o k response
func (o *DeleteV1AdminPoliciesOK) WithPayload(payload string) *DeleteV1AdminPoliciesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete v1 admin policies o k response
func (o *DeleteV1AdminPoliciesOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteV1AdminPoliciesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteV1AdminPoliciesUnauthorizedCode is the HTTP code returned for type DeleteV1AdminPoliciesUnauthorized
const DeleteV1AdminPoliciesUnauthorizedCode int = 401

/*DeleteV1AdminPoliciesUnauthorized Unauthorized

swagger:response deleteV1AdminPoliciesUnauthorized
*/
type DeleteV1AdminPoliciesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteV1AdminPoliciesUnauthorized creates DeleteV1AdminPoliciesUnauthorized with default headers values
func NewDeleteV1AdminPoliciesUnauthorized() *DeleteV1AdminPoliciesUnauthorized {

	return &DeleteV1AdminPoliciesUnauthorized{}
}

// WithPayload adds the payload to the delete v1 admin policies unauthorized response
func (o *DeleteV1AdminPoliciesUnauthorized) WithPayload(payload string) *DeleteV1AdminPoliciesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete v1 admin policies unauthorized response
func (o *DeleteV1AdminPoliciesUnauthorized) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteV1AdminPoliciesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteV1AdminPoliciesForbiddenCode is the HTTP code returned for type DeleteV1AdminPoliciesForbidden
const DeleteV1AdminPoliciesForbiddenCode int = 403

/*DeleteV1AdminPoliciesForbidden forbidden

swagger:response deleteV1AdminPoliciesForbidden
*/
type DeleteV1AdminPoliciesForbidden struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteV1AdminPoliciesForbidden creates DeleteV1AdminPoliciesForbidden with default headers values
func NewDeleteV1AdminPoliciesForbidden() *DeleteV1AdminPoliciesForbidden {

	return &DeleteV1AdminPoliciesForbidden{}
}

// WithPayload adds the payload to the delete v1 admin policies forbidden response
func (o *DeleteV1AdminPoliciesForbidden) WithPayload(payload string) *DeleteV1AdminPoliciesForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete v1 admin policies forbidden response
func (o *DeleteV1AdminPoliciesForbidden) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteV1AdminPoliciesForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteV1AdminPoliciesNotFoundCode is the HTTP code returned for type DeleteV1AdminPoliciesNotFound
const DeleteV1AdminPoliciesNotFoundCode int = 404

/*DeleteV1AdminPoliciesNotFound The specified resource was not found

swagger:response deleteV1AdminPoliciesNotFound
*/
type DeleteV1AdminPoliciesNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteV1AdminPoliciesNotFound creates DeleteV1AdminPoliciesNotFound with default headers values
func NewDeleteV1AdminPoliciesNotFound() *DeleteV1AdminPoliciesNotFound {

	return &DeleteV1AdminPoliciesNotFound{}
}

// WithPayload adds the payload to the delete v1 admin policies not found response
func (o *DeleteV1AdminPoliciesNotFound) WithPayload(payload string) *DeleteV1AdminPoliciesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete v1 admin policies not found response
func (o *DeleteV1AdminPoliciesNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteV1AdminPoliciesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteV1AdminPoliciesInternalServerErrorCode is the HTTP code returned for type DeleteV1AdminPoliciesInternalServerError
const DeleteV1AdminPoliciesInternalServerErrorCode int = 500

/*DeleteV1AdminPoliciesInternalServerError For unknown or unanticipated issues

swagger:response deleteV1AdminPoliciesInternalServerError
*/
type DeleteV1AdminPoliciesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteV1AdminPoliciesInternalServerError creates DeleteV1AdminPoliciesInternalServerError with default headers values
func NewDeleteV1AdminPoliciesInternalServerError() *DeleteV1AdminPoliciesInternalServerError {

	return &DeleteV1AdminPoliciesInternalServerError{}
}

// WithPayload adds the payload to the delete v1 admin policies internal server error response
func (o *DeleteV1AdminPoliciesInternalServerError) WithPayload(payload string) *DeleteV1AdminPoliciesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete v1 admin policies internal server error response
func (o *DeleteV1AdminPoliciesInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteV1AdminPoliciesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
