// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDeleteV1AdminRolesRoleParams creates a new DeleteV1AdminRolesRoleParams object
// no default values defined in spec.
func NewDeleteV1AdminRolesRoleParams() DeleteV1AdminRolesRoleParams {

	return DeleteV1AdminRolesRoleParams{}
}

// DeleteV1AdminRolesRoleParams contains all the bound params for the delete v1 admin roles role operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteV1AdminRolesRole
type DeleteV1AdminRolesRoleParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Name of the Role
	  Required: true
	  In: path
	*/
	Role string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteV1AdminRolesRoleParams() beforehand.
func (o *DeleteV1AdminRolesRoleParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rRole, rhkRole, _ := route.Params.GetOK("role")
	if err := o.bindRole(rRole, rhkRole, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindRole binds and validates parameter Role from path.
func (o *DeleteV1AdminRolesRoleParams) bindRole(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Role = raw

	return nil
}
