// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/momper14/edgex-restapp/models"
)

// DeleteV1AdminUsersUserHandlerFunc turns a function with the right signature into a delete v1 admin users user handler
type DeleteV1AdminUsersUserHandlerFunc func(DeleteV1AdminUsersUserParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteV1AdminUsersUserHandlerFunc) Handle(params DeleteV1AdminUsersUserParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// DeleteV1AdminUsersUserHandler interface for that can handle valid delete v1 admin users user params
type DeleteV1AdminUsersUserHandler interface {
	Handle(DeleteV1AdminUsersUserParams, *models.User) middleware.Responder
}

// NewDeleteV1AdminUsersUser creates a new http.Handler for the delete v1 admin users user operation
func NewDeleteV1AdminUsersUser(ctx *middleware.Context, handler DeleteV1AdminUsersUserHandler) *DeleteV1AdminUsersUser {
	return &DeleteV1AdminUsersUser{Context: ctx, Handler: handler}
}

/*DeleteV1AdminUsersUser swagger:route DELETE /v1/admin/users/{user} deleteV1AdminUsersUser

Deletes the user

*/
type DeleteV1AdminUsersUser struct {
	Context *middleware.Context
	Handler DeleteV1AdminUsersUserHandler
}

func (o *DeleteV1AdminUsersUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteV1AdminUsersUserParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
