// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/momper14/edgex-restapp/models"
)

// DeleteV1AdminPoliciesHandlerFunc turns a function with the right signature into a delete v1 admin policies handler
type DeleteV1AdminPoliciesHandlerFunc func(DeleteV1AdminPoliciesParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteV1AdminPoliciesHandlerFunc) Handle(params DeleteV1AdminPoliciesParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// DeleteV1AdminPoliciesHandler interface for that can handle valid delete v1 admin policies params
type DeleteV1AdminPoliciesHandler interface {
	Handle(DeleteV1AdminPoliciesParams, *models.User) middleware.Responder
}

// NewDeleteV1AdminPolicies creates a new http.Handler for the delete v1 admin policies operation
func NewDeleteV1AdminPolicies(ctx *middleware.Context, handler DeleteV1AdminPoliciesHandler) *DeleteV1AdminPolicies {
	return &DeleteV1AdminPolicies{Context: ctx, Handler: handler}
}

/*DeleteV1AdminPolicies swagger:route DELETE /v1/admin/policies deleteV1AdminPolicies

Deletes the policy

*/
type DeleteV1AdminPolicies struct {
	Context *middleware.Context
	Handler DeleteV1AdminPoliciesHandler
}

func (o *DeleteV1AdminPolicies) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteV1AdminPoliciesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
