// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/momper14/edgex-restapp/models"
)

// GetV1AdminUsersOKCode is the HTTP code returned for type GetV1AdminUsersOK
const GetV1AdminUsersOKCode int = 200

/*GetV1AdminUsersOK Ok

swagger:response getV1AdminUsersOK
*/
type GetV1AdminUsersOK struct {

	/*
	  In: Body
	*/
	Payload []*models.User `json:"body,omitempty"`
}

// NewGetV1AdminUsersOK creates GetV1AdminUsersOK with default headers values
func NewGetV1AdminUsersOK() *GetV1AdminUsersOK {

	return &GetV1AdminUsersOK{}
}

// WithPayload adds the payload to the get v1 admin users o k response
func (o *GetV1AdminUsersOK) WithPayload(payload []*models.User) *GetV1AdminUsersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 admin users o k response
func (o *GetV1AdminUsersOK) SetPayload(payload []*models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1AdminUsersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.User, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1AdminUsersUnauthorizedCode is the HTTP code returned for type GetV1AdminUsersUnauthorized
const GetV1AdminUsersUnauthorizedCode int = 401

/*GetV1AdminUsersUnauthorized Unauthorized

swagger:response getV1AdminUsersUnauthorized
*/
type GetV1AdminUsersUnauthorized struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1AdminUsersUnauthorized creates GetV1AdminUsersUnauthorized with default headers values
func NewGetV1AdminUsersUnauthorized() *GetV1AdminUsersUnauthorized {

	return &GetV1AdminUsersUnauthorized{}
}

// WithPayload adds the payload to the get v1 admin users unauthorized response
func (o *GetV1AdminUsersUnauthorized) WithPayload(payload string) *GetV1AdminUsersUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 admin users unauthorized response
func (o *GetV1AdminUsersUnauthorized) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1AdminUsersUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1AdminUsersForbiddenCode is the HTTP code returned for type GetV1AdminUsersForbidden
const GetV1AdminUsersForbiddenCode int = 403

/*GetV1AdminUsersForbidden forbidden

swagger:response getV1AdminUsersForbidden
*/
type GetV1AdminUsersForbidden struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1AdminUsersForbidden creates GetV1AdminUsersForbidden with default headers values
func NewGetV1AdminUsersForbidden() *GetV1AdminUsersForbidden {

	return &GetV1AdminUsersForbidden{}
}

// WithPayload adds the payload to the get v1 admin users forbidden response
func (o *GetV1AdminUsersForbidden) WithPayload(payload string) *GetV1AdminUsersForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 admin users forbidden response
func (o *GetV1AdminUsersForbidden) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1AdminUsersForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1AdminUsersInternalServerErrorCode is the HTTP code returned for type GetV1AdminUsersInternalServerError
const GetV1AdminUsersInternalServerErrorCode int = 500

/*GetV1AdminUsersInternalServerError For unknown or unanticipated issues

swagger:response getV1AdminUsersInternalServerError
*/
type GetV1AdminUsersInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1AdminUsersInternalServerError creates GetV1AdminUsersInternalServerError with default headers values
func NewGetV1AdminUsersInternalServerError() *GetV1AdminUsersInternalServerError {

	return &GetV1AdminUsersInternalServerError{}
}

// WithPayload adds the payload to the get v1 admin users internal server error response
func (o *GetV1AdminUsersInternalServerError) WithPayload(payload string) *GetV1AdminUsersInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 admin users internal server error response
func (o *GetV1AdminUsersInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1AdminUsersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
