// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/momper14/edgex-restapp/models"
)

// GetV1AdminUsersHandlerFunc turns a function with the right signature into a get v1 admin users handler
type GetV1AdminUsersHandlerFunc func(GetV1AdminUsersParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetV1AdminUsersHandlerFunc) Handle(params GetV1AdminUsersParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetV1AdminUsersHandler interface for that can handle valid get v1 admin users params
type GetV1AdminUsersHandler interface {
	Handle(GetV1AdminUsersParams, *models.User) middleware.Responder
}

// NewGetV1AdminUsers creates a new http.Handler for the get v1 admin users operation
func NewGetV1AdminUsers(ctx *middleware.Context, handler GetV1AdminUsersHandler) *GetV1AdminUsers {
	return &GetV1AdminUsers{Context: ctx, Handler: handler}
}

/*GetV1AdminUsers swagger:route GET /v1/admin/users getV1AdminUsers

Find all Users

*/
type GetV1AdminUsers struct {
	Context *middleware.Context
	Handler GetV1AdminUsersHandler
}

func (o *GetV1AdminUsers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetV1AdminUsersParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
