// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/momper14/edgex-restapp/models"
)

// GetV1DevicesDeviceCommandsCommandHandlerFunc turns a function with the right signature into a get v1 devices device commands command handler
type GetV1DevicesDeviceCommandsCommandHandlerFunc func(GetV1DevicesDeviceCommandsCommandParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetV1DevicesDeviceCommandsCommandHandlerFunc) Handle(params GetV1DevicesDeviceCommandsCommandParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetV1DevicesDeviceCommandsCommandHandler interface for that can handle valid get v1 devices device commands command params
type GetV1DevicesDeviceCommandsCommandHandler interface {
	Handle(GetV1DevicesDeviceCommandsCommandParams, *models.User) middleware.Responder
}

// NewGetV1DevicesDeviceCommandsCommand creates a new http.Handler for the get v1 devices device commands command operation
func NewGetV1DevicesDeviceCommandsCommand(ctx *middleware.Context, handler GetV1DevicesDeviceCommandsCommandHandler) *GetV1DevicesDeviceCommandsCommand {
	return &GetV1DevicesDeviceCommandsCommand{Context: ctx, Handler: handler}
}

/*GetV1DevicesDeviceCommandsCommand swagger:route GET /v1/devices/{device}/commands/{command} getV1DevicesDeviceCommandsCommand

Issue the GET command referenced by the command name to the device/sensor.

*/
type GetV1DevicesDeviceCommandsCommand struct {
	Context *middleware.Context
	Handler GetV1DevicesDeviceCommandsCommandHandler
}

func (o *GetV1DevicesDeviceCommandsCommand) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetV1DevicesDeviceCommandsCommandParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
