// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/momper14/edgex-restapp/models"
)

// GetV1DevicesDeviceHandlerFunc turns a function with the right signature into a get v1 devices device handler
type GetV1DevicesDeviceHandlerFunc func(GetV1DevicesDeviceParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetV1DevicesDeviceHandlerFunc) Handle(params GetV1DevicesDeviceParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetV1DevicesDeviceHandler interface for that can handle valid get v1 devices device params
type GetV1DevicesDeviceHandler interface {
	Handle(GetV1DevicesDeviceParams, *models.User) middleware.Responder
}

// NewGetV1DevicesDevice creates a new http.Handler for the get v1 devices device operation
func NewGetV1DevicesDevice(ctx *middleware.Context, handler GetV1DevicesDeviceHandler) *GetV1DevicesDevice {
	return &GetV1DevicesDevice{Context: ctx, Handler: handler}
}

/*GetV1DevicesDevice swagger:route GET /v1/devices/{device} getV1DevicesDevice

Find device by name

*/
type GetV1DevicesDevice struct {
	Context *middleware.Context
	Handler GetV1DevicesDeviceHandler
}

func (o *GetV1DevicesDevice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetV1DevicesDeviceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
