// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/momper14/edgex-restapp/models"
)

// GetV1DevicesDeviceProfileOKCode is the HTTP code returned for type GetV1DevicesDeviceProfileOK
const GetV1DevicesDeviceProfileOKCode int = 200

/*GetV1DevicesDeviceProfileOK Ok

swagger:response getV1DevicesDeviceProfileOK
*/
type GetV1DevicesDeviceProfileOK struct {

	/*
	  In: Body
	*/
	Payload *models.DeviceProfile `json:"body,omitempty"`
}

// NewGetV1DevicesDeviceProfileOK creates GetV1DevicesDeviceProfileOK with default headers values
func NewGetV1DevicesDeviceProfileOK() *GetV1DevicesDeviceProfileOK {

	return &GetV1DevicesDeviceProfileOK{}
}

// WithPayload adds the payload to the get v1 devices device profile o k response
func (o *GetV1DevicesDeviceProfileOK) WithPayload(payload *models.DeviceProfile) *GetV1DevicesDeviceProfileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 devices device profile o k response
func (o *GetV1DevicesDeviceProfileOK) SetPayload(payload *models.DeviceProfile) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1DevicesDeviceProfileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetV1DevicesDeviceProfileUnauthorizedCode is the HTTP code returned for type GetV1DevicesDeviceProfileUnauthorized
const GetV1DevicesDeviceProfileUnauthorizedCode int = 401

/*GetV1DevicesDeviceProfileUnauthorized Unauthorized

swagger:response getV1DevicesDeviceProfileUnauthorized
*/
type GetV1DevicesDeviceProfileUnauthorized struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1DevicesDeviceProfileUnauthorized creates GetV1DevicesDeviceProfileUnauthorized with default headers values
func NewGetV1DevicesDeviceProfileUnauthorized() *GetV1DevicesDeviceProfileUnauthorized {

	return &GetV1DevicesDeviceProfileUnauthorized{}
}

// WithPayload adds the payload to the get v1 devices device profile unauthorized response
func (o *GetV1DevicesDeviceProfileUnauthorized) WithPayload(payload string) *GetV1DevicesDeviceProfileUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 devices device profile unauthorized response
func (o *GetV1DevicesDeviceProfileUnauthorized) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1DevicesDeviceProfileUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1DevicesDeviceProfileForbiddenCode is the HTTP code returned for type GetV1DevicesDeviceProfileForbidden
const GetV1DevicesDeviceProfileForbiddenCode int = 403

/*GetV1DevicesDeviceProfileForbidden forbidden

swagger:response getV1DevicesDeviceProfileForbidden
*/
type GetV1DevicesDeviceProfileForbidden struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1DevicesDeviceProfileForbidden creates GetV1DevicesDeviceProfileForbidden with default headers values
func NewGetV1DevicesDeviceProfileForbidden() *GetV1DevicesDeviceProfileForbidden {

	return &GetV1DevicesDeviceProfileForbidden{}
}

// WithPayload adds the payload to the get v1 devices device profile forbidden response
func (o *GetV1DevicesDeviceProfileForbidden) WithPayload(payload string) *GetV1DevicesDeviceProfileForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 devices device profile forbidden response
func (o *GetV1DevicesDeviceProfileForbidden) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1DevicesDeviceProfileForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1DevicesDeviceProfileNotFoundCode is the HTTP code returned for type GetV1DevicesDeviceProfileNotFound
const GetV1DevicesDeviceProfileNotFoundCode int = 404

/*GetV1DevicesDeviceProfileNotFound The specified resource was not found

swagger:response getV1DevicesDeviceProfileNotFound
*/
type GetV1DevicesDeviceProfileNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1DevicesDeviceProfileNotFound creates GetV1DevicesDeviceProfileNotFound with default headers values
func NewGetV1DevicesDeviceProfileNotFound() *GetV1DevicesDeviceProfileNotFound {

	return &GetV1DevicesDeviceProfileNotFound{}
}

// WithPayload adds the payload to the get v1 devices device profile not found response
func (o *GetV1DevicesDeviceProfileNotFound) WithPayload(payload string) *GetV1DevicesDeviceProfileNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 devices device profile not found response
func (o *GetV1DevicesDeviceProfileNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1DevicesDeviceProfileNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1DevicesDeviceProfileInternalServerErrorCode is the HTTP code returned for type GetV1DevicesDeviceProfileInternalServerError
const GetV1DevicesDeviceProfileInternalServerErrorCode int = 500

/*GetV1DevicesDeviceProfileInternalServerError For unknown or unanticipated issues

swagger:response getV1DevicesDeviceProfileInternalServerError
*/
type GetV1DevicesDeviceProfileInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1DevicesDeviceProfileInternalServerError creates GetV1DevicesDeviceProfileInternalServerError with default headers values
func NewGetV1DevicesDeviceProfileInternalServerError() *GetV1DevicesDeviceProfileInternalServerError {

	return &GetV1DevicesDeviceProfileInternalServerError{}
}

// WithPayload adds the payload to the get v1 devices device profile internal server error response
func (o *GetV1DevicesDeviceProfileInternalServerError) WithPayload(payload string) *GetV1DevicesDeviceProfileInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 devices device profile internal server error response
func (o *GetV1DevicesDeviceProfileInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1DevicesDeviceProfileInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
