// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/momper14/edgex-restapp/models"
)

// GetV1DevicesHandlerFunc turns a function with the right signature into a get v1 devices handler
type GetV1DevicesHandlerFunc func(GetV1DevicesParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetV1DevicesHandlerFunc) Handle(params GetV1DevicesParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetV1DevicesHandler interface for that can handle valid get v1 devices params
type GetV1DevicesHandler interface {
	Handle(GetV1DevicesParams, *models.User) middleware.Responder
}

// NewGetV1Devices creates a new http.Handler for the get v1 devices operation
func NewGetV1Devices(ctx *middleware.Context, handler GetV1DevicesHandler) *GetV1Devices {
	return &GetV1Devices{Context: ctx, Handler: handler}
}

/*GetV1Devices swagger:route GET /v1/devices getV1Devices

Find all devices

*/
type GetV1Devices struct {
	Context *middleware.Context
	Handler GetV1DevicesHandler
}

func (o *GetV1Devices) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetV1DevicesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
