// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/momper14/edgex-restapp/models"
)

// GetV1AdminPoliciesHandlerFunc turns a function with the right signature into a get v1 admin policies handler
type GetV1AdminPoliciesHandlerFunc func(GetV1AdminPoliciesParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetV1AdminPoliciesHandlerFunc) Handle(params GetV1AdminPoliciesParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetV1AdminPoliciesHandler interface for that can handle valid get v1 admin policies params
type GetV1AdminPoliciesHandler interface {
	Handle(GetV1AdminPoliciesParams, *models.User) middleware.Responder
}

// NewGetV1AdminPolicies creates a new http.Handler for the get v1 admin policies operation
func NewGetV1AdminPolicies(ctx *middleware.Context, handler GetV1AdminPoliciesHandler) *GetV1AdminPolicies {
	return &GetV1AdminPolicies{Context: ctx, Handler: handler}
}

/*GetV1AdminPolicies swagger:route GET /v1/admin/policies getV1AdminPolicies

Find all policies

*/
type GetV1AdminPolicies struct {
	Context *middleware.Context
	Handler GetV1AdminPoliciesHandler
}

func (o *GetV1AdminPolicies) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetV1AdminPoliciesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
