// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/momper14/edgex-restapp/models"
)

// GetV1AdminRolesOKCode is the HTTP code returned for type GetV1AdminRolesOK
const GetV1AdminRolesOKCode int = 200

/*GetV1AdminRolesOK Ok

swagger:response getV1AdminRolesOK
*/
type GetV1AdminRolesOK struct {

	/*
	  In: Body
	*/
	Payload []models.Role `json:"body,omitempty"`
}

// NewGetV1AdminRolesOK creates GetV1AdminRolesOK with default headers values
func NewGetV1AdminRolesOK() *GetV1AdminRolesOK {

	return &GetV1AdminRolesOK{}
}

// WithPayload adds the payload to the get v1 admin roles o k response
func (o *GetV1AdminRolesOK) WithPayload(payload []models.Role) *GetV1AdminRolesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 admin roles o k response
func (o *GetV1AdminRolesOK) SetPayload(payload []models.Role) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1AdminRolesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]models.Role, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1AdminRolesUnauthorizedCode is the HTTP code returned for type GetV1AdminRolesUnauthorized
const GetV1AdminRolesUnauthorizedCode int = 401

/*GetV1AdminRolesUnauthorized Unauthorized

swagger:response getV1AdminRolesUnauthorized
*/
type GetV1AdminRolesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1AdminRolesUnauthorized creates GetV1AdminRolesUnauthorized with default headers values
func NewGetV1AdminRolesUnauthorized() *GetV1AdminRolesUnauthorized {

	return &GetV1AdminRolesUnauthorized{}
}

// WithPayload adds the payload to the get v1 admin roles unauthorized response
func (o *GetV1AdminRolesUnauthorized) WithPayload(payload string) *GetV1AdminRolesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 admin roles unauthorized response
func (o *GetV1AdminRolesUnauthorized) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1AdminRolesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1AdminRolesForbiddenCode is the HTTP code returned for type GetV1AdminRolesForbidden
const GetV1AdminRolesForbiddenCode int = 403

/*GetV1AdminRolesForbidden forbidden

swagger:response getV1AdminRolesForbidden
*/
type GetV1AdminRolesForbidden struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1AdminRolesForbidden creates GetV1AdminRolesForbidden with default headers values
func NewGetV1AdminRolesForbidden() *GetV1AdminRolesForbidden {

	return &GetV1AdminRolesForbidden{}
}

// WithPayload adds the payload to the get v1 admin roles forbidden response
func (o *GetV1AdminRolesForbidden) WithPayload(payload string) *GetV1AdminRolesForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 admin roles forbidden response
func (o *GetV1AdminRolesForbidden) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1AdminRolesForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1AdminRolesInternalServerErrorCode is the HTTP code returned for type GetV1AdminRolesInternalServerError
const GetV1AdminRolesInternalServerErrorCode int = 500

/*GetV1AdminRolesInternalServerError For unknown or unanticipated issues

swagger:response getV1AdminRolesInternalServerError
*/
type GetV1AdminRolesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1AdminRolesInternalServerError creates GetV1AdminRolesInternalServerError with default headers values
func NewGetV1AdminRolesInternalServerError() *GetV1AdminRolesInternalServerError {

	return &GetV1AdminRolesInternalServerError{}
}

// WithPayload adds the payload to the get v1 admin roles internal server error response
func (o *GetV1AdminRolesInternalServerError) WithPayload(payload string) *GetV1AdminRolesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 admin roles internal server error response
func (o *GetV1AdminRolesInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1AdminRolesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
