// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/momper14/edgex-restapp/models"
)

// GetV1AdminRolesRoleUsersHandlerFunc turns a function with the right signature into a get v1 admin roles role users handler
type GetV1AdminRolesRoleUsersHandlerFunc func(GetV1AdminRolesRoleUsersParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetV1AdminRolesRoleUsersHandlerFunc) Handle(params GetV1AdminRolesRoleUsersParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetV1AdminRolesRoleUsersHandler interface for that can handle valid get v1 admin roles role users params
type GetV1AdminRolesRoleUsersHandler interface {
	Handle(GetV1AdminRolesRoleUsersParams, *models.User) middleware.Responder
}

// NewGetV1AdminRolesRoleUsers creates a new http.Handler for the get v1 admin roles role users operation
func NewGetV1AdminRolesRoleUsers(ctx *middleware.Context, handler GetV1AdminRolesRoleUsersHandler) *GetV1AdminRolesRoleUsers {
	return &GetV1AdminRolesRoleUsers{Context: ctx, Handler: handler}
}

/*GetV1AdminRolesRoleUsers swagger:route GET /v1/admin/roles/{role}/users getV1AdminRolesRoleUsers

Finds all Users associated with the role

*/
type GetV1AdminRolesRoleUsers struct {
	Context *middleware.Context
	Handler GetV1AdminRolesRoleUsersHandler
}

func (o *GetV1AdminRolesRoleUsers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetV1AdminRolesRoleUsersParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
