// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/momper14/edgex-restapp/models"
)

// GetV1DevicesDeviceResourcesResourceOKCode is the HTTP code returned for type GetV1DevicesDeviceResourcesResourceOK
const GetV1DevicesDeviceResourcesResourceOKCode int = 200

/*GetV1DevicesDeviceResourcesResourceOK Ok

swagger:response getV1DevicesDeviceResourcesResourceOK
*/
type GetV1DevicesDeviceResourcesResourceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Reading `json:"body,omitempty"`
}

// NewGetV1DevicesDeviceResourcesResourceOK creates GetV1DevicesDeviceResourcesResourceOK with default headers values
func NewGetV1DevicesDeviceResourcesResourceOK() *GetV1DevicesDeviceResourcesResourceOK {

	return &GetV1DevicesDeviceResourcesResourceOK{}
}

// WithPayload adds the payload to the get v1 devices device resources resource o k response
func (o *GetV1DevicesDeviceResourcesResourceOK) WithPayload(payload *models.Reading) *GetV1DevicesDeviceResourcesResourceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 devices device resources resource o k response
func (o *GetV1DevicesDeviceResourcesResourceOK) SetPayload(payload *models.Reading) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1DevicesDeviceResourcesResourceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetV1DevicesDeviceResourcesResourceUnauthorizedCode is the HTTP code returned for type GetV1DevicesDeviceResourcesResourceUnauthorized
const GetV1DevicesDeviceResourcesResourceUnauthorizedCode int = 401

/*GetV1DevicesDeviceResourcesResourceUnauthorized Unauthorized

swagger:response getV1DevicesDeviceResourcesResourceUnauthorized
*/
type GetV1DevicesDeviceResourcesResourceUnauthorized struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1DevicesDeviceResourcesResourceUnauthorized creates GetV1DevicesDeviceResourcesResourceUnauthorized with default headers values
func NewGetV1DevicesDeviceResourcesResourceUnauthorized() *GetV1DevicesDeviceResourcesResourceUnauthorized {

	return &GetV1DevicesDeviceResourcesResourceUnauthorized{}
}

// WithPayload adds the payload to the get v1 devices device resources resource unauthorized response
func (o *GetV1DevicesDeviceResourcesResourceUnauthorized) WithPayload(payload string) *GetV1DevicesDeviceResourcesResourceUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 devices device resources resource unauthorized response
func (o *GetV1DevicesDeviceResourcesResourceUnauthorized) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1DevicesDeviceResourcesResourceUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1DevicesDeviceResourcesResourceForbiddenCode is the HTTP code returned for type GetV1DevicesDeviceResourcesResourceForbidden
const GetV1DevicesDeviceResourcesResourceForbiddenCode int = 403

/*GetV1DevicesDeviceResourcesResourceForbidden forbidden

swagger:response getV1DevicesDeviceResourcesResourceForbidden
*/
type GetV1DevicesDeviceResourcesResourceForbidden struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1DevicesDeviceResourcesResourceForbidden creates GetV1DevicesDeviceResourcesResourceForbidden with default headers values
func NewGetV1DevicesDeviceResourcesResourceForbidden() *GetV1DevicesDeviceResourcesResourceForbidden {

	return &GetV1DevicesDeviceResourcesResourceForbidden{}
}

// WithPayload adds the payload to the get v1 devices device resources resource forbidden response
func (o *GetV1DevicesDeviceResourcesResourceForbidden) WithPayload(payload string) *GetV1DevicesDeviceResourcesResourceForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 devices device resources resource forbidden response
func (o *GetV1DevicesDeviceResourcesResourceForbidden) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1DevicesDeviceResourcesResourceForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1DevicesDeviceResourcesResourceNotFoundCode is the HTTP code returned for type GetV1DevicesDeviceResourcesResourceNotFound
const GetV1DevicesDeviceResourcesResourceNotFoundCode int = 404

/*GetV1DevicesDeviceResourcesResourceNotFound The specified resource was not found

swagger:response getV1DevicesDeviceResourcesResourceNotFound
*/
type GetV1DevicesDeviceResourcesResourceNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1DevicesDeviceResourcesResourceNotFound creates GetV1DevicesDeviceResourcesResourceNotFound with default headers values
func NewGetV1DevicesDeviceResourcesResourceNotFound() *GetV1DevicesDeviceResourcesResourceNotFound {

	return &GetV1DevicesDeviceResourcesResourceNotFound{}
}

// WithPayload adds the payload to the get v1 devices device resources resource not found response
func (o *GetV1DevicesDeviceResourcesResourceNotFound) WithPayload(payload string) *GetV1DevicesDeviceResourcesResourceNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 devices device resources resource not found response
func (o *GetV1DevicesDeviceResourcesResourceNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1DevicesDeviceResourcesResourceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1DevicesDeviceResourcesResourceInternalServerErrorCode is the HTTP code returned for type GetV1DevicesDeviceResourcesResourceInternalServerError
const GetV1DevicesDeviceResourcesResourceInternalServerErrorCode int = 500

/*GetV1DevicesDeviceResourcesResourceInternalServerError For unknown or unanticipated issues

swagger:response getV1DevicesDeviceResourcesResourceInternalServerError
*/
type GetV1DevicesDeviceResourcesResourceInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1DevicesDeviceResourcesResourceInternalServerError creates GetV1DevicesDeviceResourcesResourceInternalServerError with default headers values
func NewGetV1DevicesDeviceResourcesResourceInternalServerError() *GetV1DevicesDeviceResourcesResourceInternalServerError {

	return &GetV1DevicesDeviceResourcesResourceInternalServerError{}
}

// WithPayload adds the payload to the get v1 devices device resources resource internal server error response
func (o *GetV1DevicesDeviceResourcesResourceInternalServerError) WithPayload(payload string) *GetV1DevicesDeviceResourcesResourceInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 devices device resources resource internal server error response
func (o *GetV1DevicesDeviceResourcesResourceInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1DevicesDeviceResourcesResourceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
