// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/momper14/edgex-restapp/models"
)

// GetV1DevicesOKCode is the HTTP code returned for type GetV1DevicesOK
const GetV1DevicesOKCode int = 200

/*GetV1DevicesOK Ok

swagger:response getV1DevicesOK
*/
type GetV1DevicesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Device `json:"body,omitempty"`
}

// NewGetV1DevicesOK creates GetV1DevicesOK with default headers values
func NewGetV1DevicesOK() *GetV1DevicesOK {

	return &GetV1DevicesOK{}
}

// WithPayload adds the payload to the get v1 devices o k response
func (o *GetV1DevicesOK) WithPayload(payload []*models.Device) *GetV1DevicesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 devices o k response
func (o *GetV1DevicesOK) SetPayload(payload []*models.Device) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1DevicesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Device, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1DevicesUnauthorizedCode is the HTTP code returned for type GetV1DevicesUnauthorized
const GetV1DevicesUnauthorizedCode int = 401

/*GetV1DevicesUnauthorized Unauthorized

swagger:response getV1DevicesUnauthorized
*/
type GetV1DevicesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1DevicesUnauthorized creates GetV1DevicesUnauthorized with default headers values
func NewGetV1DevicesUnauthorized() *GetV1DevicesUnauthorized {

	return &GetV1DevicesUnauthorized{}
}

// WithPayload adds the payload to the get v1 devices unauthorized response
func (o *GetV1DevicesUnauthorized) WithPayload(payload string) *GetV1DevicesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 devices unauthorized response
func (o *GetV1DevicesUnauthorized) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1DevicesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1DevicesForbiddenCode is the HTTP code returned for type GetV1DevicesForbidden
const GetV1DevicesForbiddenCode int = 403

/*GetV1DevicesForbidden forbidden

swagger:response getV1DevicesForbidden
*/
type GetV1DevicesForbidden struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1DevicesForbidden creates GetV1DevicesForbidden with default headers values
func NewGetV1DevicesForbidden() *GetV1DevicesForbidden {

	return &GetV1DevicesForbidden{}
}

// WithPayload adds the payload to the get v1 devices forbidden response
func (o *GetV1DevicesForbidden) WithPayload(payload string) *GetV1DevicesForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 devices forbidden response
func (o *GetV1DevicesForbidden) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1DevicesForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1DevicesInternalServerErrorCode is the HTTP code returned for type GetV1DevicesInternalServerError
const GetV1DevicesInternalServerErrorCode int = 500

/*GetV1DevicesInternalServerError For unknown or unanticipated issues

swagger:response getV1DevicesInternalServerError
*/
type GetV1DevicesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1DevicesInternalServerError creates GetV1DevicesInternalServerError with default headers values
func NewGetV1DevicesInternalServerError() *GetV1DevicesInternalServerError {

	return &GetV1DevicesInternalServerError{}
}

// WithPayload adds the payload to the get v1 devices internal server error response
func (o *GetV1DevicesInternalServerError) WithPayload(payload string) *GetV1DevicesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 devices internal server error response
func (o *GetV1DevicesInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1DevicesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
