// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/momper14/edgex-restapp/models"
)

// GetV1DevicesDeviceResourcesResourceHandlerFunc turns a function with the right signature into a get v1 devices device resources resource handler
type GetV1DevicesDeviceResourcesResourceHandlerFunc func(GetV1DevicesDeviceResourcesResourceParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetV1DevicesDeviceResourcesResourceHandlerFunc) Handle(params GetV1DevicesDeviceResourcesResourceParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetV1DevicesDeviceResourcesResourceHandler interface for that can handle valid get v1 devices device resources resource params
type GetV1DevicesDeviceResourcesResourceHandler interface {
	Handle(GetV1DevicesDeviceResourcesResourceParams, *models.User) middleware.Responder
}

// NewGetV1DevicesDeviceResourcesResource creates a new http.Handler for the get v1 devices device resources resource operation
func NewGetV1DevicesDeviceResourcesResource(ctx *middleware.Context, handler GetV1DevicesDeviceResourcesResourceHandler) *GetV1DevicesDeviceResourcesResource {
	return &GetV1DevicesDeviceResourcesResource{Context: ctx, Handler: handler}
}

/*GetV1DevicesDeviceResourcesResource swagger:route GET /v1/devices/{device}/resources/{resource} getV1DevicesDeviceResourcesResource

Get the last resource reading from the device

*/
type GetV1DevicesDeviceResourcesResource struct {
	Context *middleware.Context
	Handler GetV1DevicesDeviceResourcesResourceHandler
}

func (o *GetV1DevicesDeviceResourcesResource) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetV1DevicesDeviceResourcesResourceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
