// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/momper14/edgex-restapp/models"
)

// GetV1DevicesDeviceValuedescriptorsOKCode is the HTTP code returned for type GetV1DevicesDeviceValuedescriptorsOK
const GetV1DevicesDeviceValuedescriptorsOKCode int = 200

/*GetV1DevicesDeviceValuedescriptorsOK Ok

swagger:response getV1DevicesDeviceValuedescriptorsOK
*/
type GetV1DevicesDeviceValuedescriptorsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.ValueDescriptor `json:"body,omitempty"`
}

// NewGetV1DevicesDeviceValuedescriptorsOK creates GetV1DevicesDeviceValuedescriptorsOK with default headers values
func NewGetV1DevicesDeviceValuedescriptorsOK() *GetV1DevicesDeviceValuedescriptorsOK {

	return &GetV1DevicesDeviceValuedescriptorsOK{}
}

// WithPayload adds the payload to the get v1 devices device valuedescriptors o k response
func (o *GetV1DevicesDeviceValuedescriptorsOK) WithPayload(payload []*models.ValueDescriptor) *GetV1DevicesDeviceValuedescriptorsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 devices device valuedescriptors o k response
func (o *GetV1DevicesDeviceValuedescriptorsOK) SetPayload(payload []*models.ValueDescriptor) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1DevicesDeviceValuedescriptorsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.ValueDescriptor, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1DevicesDeviceValuedescriptorsUnauthorizedCode is the HTTP code returned for type GetV1DevicesDeviceValuedescriptorsUnauthorized
const GetV1DevicesDeviceValuedescriptorsUnauthorizedCode int = 401

/*GetV1DevicesDeviceValuedescriptorsUnauthorized Unauthorized

swagger:response getV1DevicesDeviceValuedescriptorsUnauthorized
*/
type GetV1DevicesDeviceValuedescriptorsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1DevicesDeviceValuedescriptorsUnauthorized creates GetV1DevicesDeviceValuedescriptorsUnauthorized with default headers values
func NewGetV1DevicesDeviceValuedescriptorsUnauthorized() *GetV1DevicesDeviceValuedescriptorsUnauthorized {

	return &GetV1DevicesDeviceValuedescriptorsUnauthorized{}
}

// WithPayload adds the payload to the get v1 devices device valuedescriptors unauthorized response
func (o *GetV1DevicesDeviceValuedescriptorsUnauthorized) WithPayload(payload string) *GetV1DevicesDeviceValuedescriptorsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 devices device valuedescriptors unauthorized response
func (o *GetV1DevicesDeviceValuedescriptorsUnauthorized) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1DevicesDeviceValuedescriptorsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1DevicesDeviceValuedescriptorsForbiddenCode is the HTTP code returned for type GetV1DevicesDeviceValuedescriptorsForbidden
const GetV1DevicesDeviceValuedescriptorsForbiddenCode int = 403

/*GetV1DevicesDeviceValuedescriptorsForbidden forbidden

swagger:response getV1DevicesDeviceValuedescriptorsForbidden
*/
type GetV1DevicesDeviceValuedescriptorsForbidden struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1DevicesDeviceValuedescriptorsForbidden creates GetV1DevicesDeviceValuedescriptorsForbidden with default headers values
func NewGetV1DevicesDeviceValuedescriptorsForbidden() *GetV1DevicesDeviceValuedescriptorsForbidden {

	return &GetV1DevicesDeviceValuedescriptorsForbidden{}
}

// WithPayload adds the payload to the get v1 devices device valuedescriptors forbidden response
func (o *GetV1DevicesDeviceValuedescriptorsForbidden) WithPayload(payload string) *GetV1DevicesDeviceValuedescriptorsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 devices device valuedescriptors forbidden response
func (o *GetV1DevicesDeviceValuedescriptorsForbidden) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1DevicesDeviceValuedescriptorsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1DevicesDeviceValuedescriptorsNotFoundCode is the HTTP code returned for type GetV1DevicesDeviceValuedescriptorsNotFound
const GetV1DevicesDeviceValuedescriptorsNotFoundCode int = 404

/*GetV1DevicesDeviceValuedescriptorsNotFound The specified resource was not found

swagger:response getV1DevicesDeviceValuedescriptorsNotFound
*/
type GetV1DevicesDeviceValuedescriptorsNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1DevicesDeviceValuedescriptorsNotFound creates GetV1DevicesDeviceValuedescriptorsNotFound with default headers values
func NewGetV1DevicesDeviceValuedescriptorsNotFound() *GetV1DevicesDeviceValuedescriptorsNotFound {

	return &GetV1DevicesDeviceValuedescriptorsNotFound{}
}

// WithPayload adds the payload to the get v1 devices device valuedescriptors not found response
func (o *GetV1DevicesDeviceValuedescriptorsNotFound) WithPayload(payload string) *GetV1DevicesDeviceValuedescriptorsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 devices device valuedescriptors not found response
func (o *GetV1DevicesDeviceValuedescriptorsNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1DevicesDeviceValuedescriptorsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1DevicesDeviceValuedescriptorsInternalServerErrorCode is the HTTP code returned for type GetV1DevicesDeviceValuedescriptorsInternalServerError
const GetV1DevicesDeviceValuedescriptorsInternalServerErrorCode int = 500

/*GetV1DevicesDeviceValuedescriptorsInternalServerError For unknown or unanticipated issues

swagger:response getV1DevicesDeviceValuedescriptorsInternalServerError
*/
type GetV1DevicesDeviceValuedescriptorsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1DevicesDeviceValuedescriptorsInternalServerError creates GetV1DevicesDeviceValuedescriptorsInternalServerError with default headers values
func NewGetV1DevicesDeviceValuedescriptorsInternalServerError() *GetV1DevicesDeviceValuedescriptorsInternalServerError {

	return &GetV1DevicesDeviceValuedescriptorsInternalServerError{}
}

// WithPayload adds the payload to the get v1 devices device valuedescriptors internal server error response
func (o *GetV1DevicesDeviceValuedescriptorsInternalServerError) WithPayload(payload string) *GetV1DevicesDeviceValuedescriptorsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 devices device valuedescriptors internal server error response
func (o *GetV1DevicesDeviceValuedescriptorsInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1DevicesDeviceValuedescriptorsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
