// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/momper14/edgex-restapp/models"
)

// GetV1AdminPoliciesOKCode is the HTTP code returned for type GetV1AdminPoliciesOK
const GetV1AdminPoliciesOKCode int = 200

/*GetV1AdminPoliciesOK Ok

swagger:response getV1AdminPoliciesOK
*/
type GetV1AdminPoliciesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Policy `json:"body,omitempty"`
}

// NewGetV1AdminPoliciesOK creates GetV1AdminPoliciesOK with default headers values
func NewGetV1AdminPoliciesOK() *GetV1AdminPoliciesOK {

	return &GetV1AdminPoliciesOK{}
}

// WithPayload adds the payload to the get v1 admin policies o k response
func (o *GetV1AdminPoliciesOK) WithPayload(payload []*models.Policy) *GetV1AdminPoliciesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 admin policies o k response
func (o *GetV1AdminPoliciesOK) SetPayload(payload []*models.Policy) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1AdminPoliciesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Policy, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1AdminPoliciesUnauthorizedCode is the HTTP code returned for type GetV1AdminPoliciesUnauthorized
const GetV1AdminPoliciesUnauthorizedCode int = 401

/*GetV1AdminPoliciesUnauthorized Unauthorized

swagger:response getV1AdminPoliciesUnauthorized
*/
type GetV1AdminPoliciesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1AdminPoliciesUnauthorized creates GetV1AdminPoliciesUnauthorized with default headers values
func NewGetV1AdminPoliciesUnauthorized() *GetV1AdminPoliciesUnauthorized {

	return &GetV1AdminPoliciesUnauthorized{}
}

// WithPayload adds the payload to the get v1 admin policies unauthorized response
func (o *GetV1AdminPoliciesUnauthorized) WithPayload(payload string) *GetV1AdminPoliciesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 admin policies unauthorized response
func (o *GetV1AdminPoliciesUnauthorized) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1AdminPoliciesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1AdminPoliciesForbiddenCode is the HTTP code returned for type GetV1AdminPoliciesForbidden
const GetV1AdminPoliciesForbiddenCode int = 403

/*GetV1AdminPoliciesForbidden forbidden

swagger:response getV1AdminPoliciesForbidden
*/
type GetV1AdminPoliciesForbidden struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1AdminPoliciesForbidden creates GetV1AdminPoliciesForbidden with default headers values
func NewGetV1AdminPoliciesForbidden() *GetV1AdminPoliciesForbidden {

	return &GetV1AdminPoliciesForbidden{}
}

// WithPayload adds the payload to the get v1 admin policies forbidden response
func (o *GetV1AdminPoliciesForbidden) WithPayload(payload string) *GetV1AdminPoliciesForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 admin policies forbidden response
func (o *GetV1AdminPoliciesForbidden) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1AdminPoliciesForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1AdminPoliciesInternalServerErrorCode is the HTTP code returned for type GetV1AdminPoliciesInternalServerError
const GetV1AdminPoliciesInternalServerErrorCode int = 500

/*GetV1AdminPoliciesInternalServerError For unknown or unanticipated issues

swagger:response getV1AdminPoliciesInternalServerError
*/
type GetV1AdminPoliciesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1AdminPoliciesInternalServerError creates GetV1AdminPoliciesInternalServerError with default headers values
func NewGetV1AdminPoliciesInternalServerError() *GetV1AdminPoliciesInternalServerError {

	return &GetV1AdminPoliciesInternalServerError{}
}

// WithPayload adds the payload to the get v1 admin policies internal server error response
func (o *GetV1AdminPoliciesInternalServerError) WithPayload(payload string) *GetV1AdminPoliciesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 admin policies internal server error response
func (o *GetV1AdminPoliciesInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1AdminPoliciesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
