// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/momper14/edgex-restapp/models"
)

// GetV1AdminRolesRoleUsersOKCode is the HTTP code returned for type GetV1AdminRolesRoleUsersOK
const GetV1AdminRolesRoleUsersOKCode int = 200

/*GetV1AdminRolesRoleUsersOK ok

swagger:response getV1AdminRolesRoleUsersOK
*/
type GetV1AdminRolesRoleUsersOK struct {

	/*
	  In: Body
	*/
	Payload []*models.User `json:"body,omitempty"`
}

// NewGetV1AdminRolesRoleUsersOK creates GetV1AdminRolesRoleUsersOK with default headers values
func NewGetV1AdminRolesRoleUsersOK() *GetV1AdminRolesRoleUsersOK {

	return &GetV1AdminRolesRoleUsersOK{}
}

// WithPayload adds the payload to the get v1 admin roles role users o k response
func (o *GetV1AdminRolesRoleUsersOK) WithPayload(payload []*models.User) *GetV1AdminRolesRoleUsersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 admin roles role users o k response
func (o *GetV1AdminRolesRoleUsersOK) SetPayload(payload []*models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1AdminRolesRoleUsersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.User, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1AdminRolesRoleUsersUnauthorizedCode is the HTTP code returned for type GetV1AdminRolesRoleUsersUnauthorized
const GetV1AdminRolesRoleUsersUnauthorizedCode int = 401

/*GetV1AdminRolesRoleUsersUnauthorized Unauthorized

swagger:response getV1AdminRolesRoleUsersUnauthorized
*/
type GetV1AdminRolesRoleUsersUnauthorized struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1AdminRolesRoleUsersUnauthorized creates GetV1AdminRolesRoleUsersUnauthorized with default headers values
func NewGetV1AdminRolesRoleUsersUnauthorized() *GetV1AdminRolesRoleUsersUnauthorized {

	return &GetV1AdminRolesRoleUsersUnauthorized{}
}

// WithPayload adds the payload to the get v1 admin roles role users unauthorized response
func (o *GetV1AdminRolesRoleUsersUnauthorized) WithPayload(payload string) *GetV1AdminRolesRoleUsersUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 admin roles role users unauthorized response
func (o *GetV1AdminRolesRoleUsersUnauthorized) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1AdminRolesRoleUsersUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1AdminRolesRoleUsersForbiddenCode is the HTTP code returned for type GetV1AdminRolesRoleUsersForbidden
const GetV1AdminRolesRoleUsersForbiddenCode int = 403

/*GetV1AdminRolesRoleUsersForbidden forbidden

swagger:response getV1AdminRolesRoleUsersForbidden
*/
type GetV1AdminRolesRoleUsersForbidden struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1AdminRolesRoleUsersForbidden creates GetV1AdminRolesRoleUsersForbidden with default headers values
func NewGetV1AdminRolesRoleUsersForbidden() *GetV1AdminRolesRoleUsersForbidden {

	return &GetV1AdminRolesRoleUsersForbidden{}
}

// WithPayload adds the payload to the get v1 admin roles role users forbidden response
func (o *GetV1AdminRolesRoleUsersForbidden) WithPayload(payload string) *GetV1AdminRolesRoleUsersForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 admin roles role users forbidden response
func (o *GetV1AdminRolesRoleUsersForbidden) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1AdminRolesRoleUsersForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1AdminRolesRoleUsersNotFoundCode is the HTTP code returned for type GetV1AdminRolesRoleUsersNotFound
const GetV1AdminRolesRoleUsersNotFoundCode int = 404

/*GetV1AdminRolesRoleUsersNotFound The specified resource was not found

swagger:response getV1AdminRolesRoleUsersNotFound
*/
type GetV1AdminRolesRoleUsersNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1AdminRolesRoleUsersNotFound creates GetV1AdminRolesRoleUsersNotFound with default headers values
func NewGetV1AdminRolesRoleUsersNotFound() *GetV1AdminRolesRoleUsersNotFound {

	return &GetV1AdminRolesRoleUsersNotFound{}
}

// WithPayload adds the payload to the get v1 admin roles role users not found response
func (o *GetV1AdminRolesRoleUsersNotFound) WithPayload(payload string) *GetV1AdminRolesRoleUsersNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 admin roles role users not found response
func (o *GetV1AdminRolesRoleUsersNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1AdminRolesRoleUsersNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1AdminRolesRoleUsersInternalServerErrorCode is the HTTP code returned for type GetV1AdminRolesRoleUsersInternalServerError
const GetV1AdminRolesRoleUsersInternalServerErrorCode int = 500

/*GetV1AdminRolesRoleUsersInternalServerError For unknown or unanticipated issues

swagger:response getV1AdminRolesRoleUsersInternalServerError
*/
type GetV1AdminRolesRoleUsersInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1AdminRolesRoleUsersInternalServerError creates GetV1AdminRolesRoleUsersInternalServerError with default headers values
func NewGetV1AdminRolesRoleUsersInternalServerError() *GetV1AdminRolesRoleUsersInternalServerError {

	return &GetV1AdminRolesRoleUsersInternalServerError{}
}

// WithPayload adds the payload to the get v1 admin roles role users internal server error response
func (o *GetV1AdminRolesRoleUsersInternalServerError) WithPayload(payload string) *GetV1AdminRolesRoleUsersInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 admin roles role users internal server error response
func (o *GetV1AdminRolesRoleUsersInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1AdminRolesRoleUsersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
