// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/momper14/edgex-restapp/models"
)

// PostV1AdminPoliciesCreatedCode is the HTTP code returned for type PostV1AdminPoliciesCreated
const PostV1AdminPoliciesCreatedCode int = 201

/*PostV1AdminPoliciesCreated Created

swagger:response postV1AdminPoliciesCreated
*/
type PostV1AdminPoliciesCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Policy `json:"body,omitempty"`
}

// NewPostV1AdminPoliciesCreated creates PostV1AdminPoliciesCreated with default headers values
func NewPostV1AdminPoliciesCreated() *PostV1AdminPoliciesCreated {

	return &PostV1AdminPoliciesCreated{}
}

// WithPayload adds the payload to the post v1 admin policies created response
func (o *PostV1AdminPoliciesCreated) WithPayload(payload *models.Policy) *PostV1AdminPoliciesCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v1 admin policies created response
func (o *PostV1AdminPoliciesCreated) SetPayload(payload *models.Policy) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostV1AdminPoliciesCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostV1AdminPoliciesUnauthorizedCode is the HTTP code returned for type PostV1AdminPoliciesUnauthorized
const PostV1AdminPoliciesUnauthorizedCode int = 401

/*PostV1AdminPoliciesUnauthorized Unauthorized

swagger:response postV1AdminPoliciesUnauthorized
*/
type PostV1AdminPoliciesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostV1AdminPoliciesUnauthorized creates PostV1AdminPoliciesUnauthorized with default headers values
func NewPostV1AdminPoliciesUnauthorized() *PostV1AdminPoliciesUnauthorized {

	return &PostV1AdminPoliciesUnauthorized{}
}

// WithPayload adds the payload to the post v1 admin policies unauthorized response
func (o *PostV1AdminPoliciesUnauthorized) WithPayload(payload string) *PostV1AdminPoliciesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v1 admin policies unauthorized response
func (o *PostV1AdminPoliciesUnauthorized) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostV1AdminPoliciesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostV1AdminPoliciesForbiddenCode is the HTTP code returned for type PostV1AdminPoliciesForbidden
const PostV1AdminPoliciesForbiddenCode int = 403

/*PostV1AdminPoliciesForbidden forbidden

swagger:response postV1AdminPoliciesForbidden
*/
type PostV1AdminPoliciesForbidden struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostV1AdminPoliciesForbidden creates PostV1AdminPoliciesForbidden with default headers values
func NewPostV1AdminPoliciesForbidden() *PostV1AdminPoliciesForbidden {

	return &PostV1AdminPoliciesForbidden{}
}

// WithPayload adds the payload to the post v1 admin policies forbidden response
func (o *PostV1AdminPoliciesForbidden) WithPayload(payload string) *PostV1AdminPoliciesForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v1 admin policies forbidden response
func (o *PostV1AdminPoliciesForbidden) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostV1AdminPoliciesForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostV1AdminPoliciesConflictCode is the HTTP code returned for type PostV1AdminPoliciesConflict
const PostV1AdminPoliciesConflictCode int = 409

/*PostV1AdminPoliciesConflict conflict

swagger:response postV1AdminPoliciesConflict
*/
type PostV1AdminPoliciesConflict struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostV1AdminPoliciesConflict creates PostV1AdminPoliciesConflict with default headers values
func NewPostV1AdminPoliciesConflict() *PostV1AdminPoliciesConflict {

	return &PostV1AdminPoliciesConflict{}
}

// WithPayload adds the payload to the post v1 admin policies conflict response
func (o *PostV1AdminPoliciesConflict) WithPayload(payload string) *PostV1AdminPoliciesConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v1 admin policies conflict response
func (o *PostV1AdminPoliciesConflict) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostV1AdminPoliciesConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostV1AdminPoliciesInternalServerErrorCode is the HTTP code returned for type PostV1AdminPoliciesInternalServerError
const PostV1AdminPoliciesInternalServerErrorCode int = 500

/*PostV1AdminPoliciesInternalServerError For unknown or unanticipated issues

swagger:response postV1AdminPoliciesInternalServerError
*/
type PostV1AdminPoliciesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostV1AdminPoliciesInternalServerError creates PostV1AdminPoliciesInternalServerError with default headers values
func NewPostV1AdminPoliciesInternalServerError() *PostV1AdminPoliciesInternalServerError {

	return &PostV1AdminPoliciesInternalServerError{}
}

// WithPayload adds the payload to the post v1 admin policies internal server error response
func (o *PostV1AdminPoliciesInternalServerError) WithPayload(payload string) *PostV1AdminPoliciesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v1 admin policies internal server error response
func (o *PostV1AdminPoliciesInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostV1AdminPoliciesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
