// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/momper14/edgex-restapp/models"
)

// PostV1AdminRolesHandlerFunc turns a function with the right signature into a post v1 admin roles handler
type PostV1AdminRolesHandlerFunc func(PostV1AdminRolesParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn PostV1AdminRolesHandlerFunc) Handle(params PostV1AdminRolesParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// PostV1AdminRolesHandler interface for that can handle valid post v1 admin roles params
type PostV1AdminRolesHandler interface {
	Handle(PostV1AdminRolesParams, *models.User) middleware.Responder
}

// NewPostV1AdminRoles creates a new http.Handler for the post v1 admin roles operation
func NewPostV1AdminRoles(ctx *middleware.Context, handler PostV1AdminRolesHandler) *PostV1AdminRoles {
	return &PostV1AdminRoles{Context: ctx, Handler: handler}
}

/*PostV1AdminRoles swagger:route POST /v1/admin/roles postV1AdminRoles

Add a new role

*/
type PostV1AdminRoles struct {
	Context *middleware.Context
	Handler PostV1AdminRolesHandler
}

func (o *PostV1AdminRoles) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostV1AdminRolesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
