// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/momper14/edgex-restapp/models"
)

// PostV1AdminPoliciesHandlerFunc turns a function with the right signature into a post v1 admin policies handler
type PostV1AdminPoliciesHandlerFunc func(PostV1AdminPoliciesParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn PostV1AdminPoliciesHandlerFunc) Handle(params PostV1AdminPoliciesParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// PostV1AdminPoliciesHandler interface for that can handle valid post v1 admin policies params
type PostV1AdminPoliciesHandler interface {
	Handle(PostV1AdminPoliciesParams, *models.User) middleware.Responder
}

// NewPostV1AdminPolicies creates a new http.Handler for the post v1 admin policies operation
func NewPostV1AdminPolicies(ctx *middleware.Context, handler PostV1AdminPoliciesHandler) *PostV1AdminPolicies {
	return &PostV1AdminPolicies{Context: ctx, Handler: handler}
}

/*PostV1AdminPolicies swagger:route POST /v1/admin/policies postV1AdminPolicies

Add a new policy

*/
type PostV1AdminPolicies struct {
	Context *middleware.Context
	Handler PostV1AdminPoliciesHandler
}

func (o *PostV1AdminPolicies) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostV1AdminPoliciesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
