// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"github.com/momper14/edgex-restapp/models"
)

// NewPutV1DevicesDeviceCommandsCommandParams creates a new PutV1DevicesDeviceCommandsCommandParams object
// no default values defined in spec.
func NewPutV1DevicesDeviceCommandsCommandParams() PutV1DevicesDeviceCommandsCommandParams {

	return PutV1DevicesDeviceCommandsCommandParams{}
}

// PutV1DevicesDeviceCommandsCommandParams contains all the bound params for the put v1 devices device commands command operation
// typically these are obtained from a http.Request
//
// swagger:parameters PutV1DevicesDeviceCommandsCommand
type PutV1DevicesDeviceCommandsCommandParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*properties for the command
	  In: body
	*/
	Body models.CommandPayload
	/*Name of the command
	  Required: true
	  In: path
	*/
	Command string
	/*The name of the device
	  Required: true
	  In: path
	*/
	Device string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutV1DevicesDeviceCommandsCommandParams() beforehand.
func (o *PutV1DevicesDeviceCommandsCommandParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.CommandPayload
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("body", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = body
			}
		}
	}
	rCommand, rhkCommand, _ := route.Params.GetOK("command")
	if err := o.bindCommand(rCommand, rhkCommand, route.Formats); err != nil {
		res = append(res, err)
	}

	rDevice, rhkDevice, _ := route.Params.GetOK("device")
	if err := o.bindDevice(rDevice, rhkDevice, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCommand binds and validates parameter Command from path.
func (o *PutV1DevicesDeviceCommandsCommandParams) bindCommand(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Command = raw

	return nil
}

// bindDevice binds and validates parameter Device from path.
func (o *PutV1DevicesDeviceCommandsCommandParams) bindDevice(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Device = raw

	return nil
}
