// Code generated by go-swagger; DO NOT EDIT.

// Package restapi iot-gateway
//
//  This is an RESTful application service for the EdgeX Foundry IoT-Gateway
//  Schemes:
//    http
//    https
//  Host: 0.0.0.0:8080
//  BasePath: /api
//  Version: 0.0.2
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//    - text/plain
//
// swagger:meta
package restapi
