// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// CommandResponse response
//
// Response from the command. Unknown schema
//
// swagger:model CommandResponse
type CommandResponse interface{}
