// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// CommandPayload commandPayload
//
// key/value properties for the command
//
// swagger:model CommandPayload
type CommandPayload map[string]interface{}

// Validate validates this command payload
func (m CommandPayload) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this command payload based on context it is used
func (m CommandPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
