// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CommandGetResponse commandgetresponse
//
// swagger:model CommandGetResponse
type CommandGetResponse struct {

	// code
	Code string `json:"code,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// expectedValues
	ExpectedValues []string `json:"expectedValues,omitempty"`
}

// Validate validates this command get response
func (m *CommandGetResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this command get response based on context it is used
func (m *CommandGetResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CommandGetResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CommandGetResponse) UnmarshalBinary(b []byte) error {
	var res CommandGetResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
