// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Reading reading
//
// Core device/sensor reading
//
// swagger:model Reading
type Reading struct {

	// name
	Name string `json:"name,omitempty"`

	// created
	Created int64 `json:"created,omitempty"`

	// modified
	Modified int64 `json:"modified,omitempty"`

	// value
	Value string `json:"value,omitempty"`

	// valueType
	ValueType string `json:"valueType,omitempty"`

	// pushed
	Pushed int64 `json:"pushed,omitempty"`
}

// Validate validates this reading
func (m *Reading) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this reading based on context it is used
func (m *Reading) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Reading) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Reading) UnmarshalBinary(b []byte) error {
	var res Reading
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
