// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResourcePropertiesValue value
//
// swagger:model ResourcePropertiesValue
type ResourcePropertiesValue struct {

	// type
	Type string `json:"type,omitempty"`

	// readWrite
	ReadWrite string `json:"readWrite,omitempty"`

	// minimum
	Minimum string `json:"minimum,omitempty"`

	// maximum
	Maximum string `json:"maximum,omitempty"`

	// defaultValue
	DefaultValue string `json:"defaultValue,omitempty"`

	// mask
	Mask uint64 `json:"mask,omitempty"`

	// shift
	Shift uint64 `json:"shift,omitempty"`

	// scale
	Scale int64 `json:"scale,omitempty"`

	// offset
	Offset int64 `json:"offset,omitempty"`

	// base
	Base int64 `json:"base,omitempty"`

	// assertion
	Assertion string `json:"assertion,omitempty"`

	// floatEncoding
	FloatEncoding string `json:"floatEncoding,omitempty"`

	// mediatype
	Mediatype string `json:"mediatype,omitempty"`
}

// Validate validates this resource properties value
func (m *ResourcePropertiesValue) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this resource properties value based on context it is used
func (m *ResourcePropertiesValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResourcePropertiesValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourcePropertiesValue) UnmarshalBinary(b []byte) error {
	var res ResourcePropertiesValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
