// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResourcePropertiesUnit unit
//
// swagger:model ResourcePropertiesUnit
type ResourcePropertiesUnit struct {

	// type
	Type string `json:"type,omitempty"`

	// readWrite
	ReadWrite string `json:"readWrite,omitempty"`

	// defaultValue
	DefaultValue string `json:"defaultValue,omitempty"`
}

// Validate validates this resource properties unit
func (m *ResourcePropertiesUnit) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this resource properties unit based on context it is used
func (m *ResourcePropertiesUnit) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResourcePropertiesUnit) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourcePropertiesUnit) UnmarshalBinary(b []byte) error {
	var res ResourcePropertiesUnit
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
