// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserUpdate user
//
// Payload to updates a user
//
// swagger:model UserUpdate
type UserUpdate struct {

	// password
	Password *string `json:"password,omitempty"`

	// name
	Role *string `json:"role,omitempty"`
}

// Validate validates this user update
func (m *UserUpdate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user update based on context it is used
func (m *UserUpdate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserUpdate) UnmarshalBinary(b []byte) error {
	var res UserUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
