// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ValueDescriptor valueDescriptor
//
// Core and MetaData value descriptor that describes device/sensor data sent and received
//
// swagger:model ValueDescriptor
type ValueDescriptor struct {

	// name
	Name string `json:"name,omitempty"`

	// labels
	Labels []string `json:"labels,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// created
	Created int64 `json:"created,omitempty"`

	// modified
	Modified int64 `json:"modified,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// uomLabel
	//
	// Unit
	UomLabel string `json:"uomLabel,omitempty"`

	// min
	Min string `json:"min,omitempty"`

	// max
	Max string `json:"max,omitempty"`

	// defaultValue
	DefaultValue string `json:"defaultValue,omitempty"`

	// formatting
	Formatting string `json:"formatting,omitempty"`
}

// Validate validates this value descriptor
func (m *ValueDescriptor) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this value descriptor based on context it is used
func (m *ValueDescriptor) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ValueDescriptor) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ValueDescriptor) UnmarshalBinary(b []byte) error {
	var res ValueDescriptor
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
